# Generated by Django 5.1.7 on 2025-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('barangay_official', 'Barangay Official'), ('personnel', 'Personnel')], default='personnel', max_length=20),
        ),
    ]
