# Generated by Django 5.2.4 on 2025-07-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='emergency_type',
            field=models.CharField(max_length=100),
        ),
    ]
