# Generated by Django 5.2.4 on 2025-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_emergencyreport_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='report_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
