# Generated by Django 5.2.4 on 2025-07-30 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlotterReport',
            fields=[
                ('report_number', models.AutoField(primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=255)),
                ('respondent_name', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('complaint', 'Complaint'), ('incident', 'Incident'), ('mediation', 'Mediation')], max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='blotter_evidence/')),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='filed', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_filed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
